x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}) (?P<message>(?s:.*))$$'

name: fastapi-observability
services:
  loki:
    container_name: loki
    image: grafana/loki:3.5.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  app-a:
    container_name: app-a
    image: ghcr.io/blueswen/fastapi-observability/app:latest
    ports:
      - "8000:8000"
    depends_on:
      - loki
    environment:
      APP_NAME: "app-a"
    logging: *default-logging

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.3.1
    ports:
      - "9090:9090"
    volumes:
      - ../config/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging

  tempo:
    container_name: tempo
    image: grafana/tempo:2.7.2
    command: [ "-config.file=/etc/tempo.yml", "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ../config/tempo/tempo.yml:/etc/tempo.yml
    depends_on:
      - loki
    logging: *default-logging

  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_DEFAULT_THEME=dark
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/fastapi-observability.json
      - GF_DATE_FORMATS_DEFAULT_TIMEZONE=Europe/Madrid
      - GF_USERS_DEFAULT_LANGUAGE=es-ES
    volumes:
      - ../config/grafana/:/etc/grafana/provisioning/datasources
      - ../config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ../config/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    logging: *default-logging
